### ISSUE TITLE
migrate to typescript

### ISSUE THREAD

**Issue by helio-frota** [obs-nebula/bdi-ts#1]
@pnaik1 we don't need to be worried about to keep the things working, in other words we can push non-working-code.

This is just a manual practice to see what happen during the migration while learning TypeScript.

A good thing to start is to rename all the files from .js to .ts and see what vscode is complaining about. :+1:

**Comment by pnaik1** [comment]
yeah , sure @helio-frota thank you

**Comment by pnaik1** [comment]
okay @helio-frota
